spring:
  datasource:
      url: jdbc:mysql://localhost:3306/adx?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: root
mybatis:
  typeAliasesPackage: com.yx.adx.domian
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true